### ISSUE TITLE
This localhost page can’t be found occurs in VS2017

### ISSUE THREAD

**Issue by shaheenaakhter** [KevinDockx/RESTfulAPIAspNetCore_Course#3]
Hi Kevin,

Using the code given in the repository from sample files,trying to invoke http://localhost:52988/api/authors ,but below error appears.Please help to fix it.I'm stuck with this error.

Decorated the authors controller class with Route[("api/authors")]

Thanks for the help.
Shaheena

This localhost page can’t be found
No webpage was found for the web address: http://localhost:52988/
Search Google for localhost 52988
HTTP ERROR 404

**Comment by KevinDockx** [comment]
Hi,

the message says "No webpage was found for the web address: http://localhost:52988/", so it looks like you're trying to open the root instead of api/authors.  There's nothing configured at the root, so that should indeed result in a "not found" error.  

If you navigate to localhost:52988/api/authors, you should get back the authors.

**Comment by shaheenaakhter** [comment]
Thanks very much for the response .Much appreciated.

**Comment by KevinDockx** [comment]
You're welcome, happy to help :)
