### ISSUE TITLE
Do you have the final set of files?

### ISSUE THREAD

**Issue by hades200082** [KevinDockx/RESTfulAPIAspNetCore_Course#6]
I've watched through your course twice now and want to start my own project. It would be great to have the final files from your course as a reference on here.

**Comment by KevinDockx** [comment]
Hi Lee, 

you can get those by downloading them from the exercises tab over at Pluralsight.  FYI: shortly after this course I started putting the finished files for courses I created since then on Github as well, next to the starter files.  I'm also going to do that for the update of this course to Core 3 (working on it as we speak :)).
